### ISSUE TITLE
Weird sporadic issue with Disasmo

### ISSUE THREAD

**Issue by MadProbe** [EgorBo/Disasmo#47]
Sometimes when I open up VS I can encounter this strange exception:
```
System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at Disasmo.MainViewModel.<RunOperationAsync>d__80.MoveNext()
```
It fixes up itself eventually but I don't understand how I get to see this problem self-fixed at all and I have no clear reasoning what's wrong about it.

**Comment by MadProbe** [comment]
I have done some research on this and with share bit of luck I have found out that this issue happens if I have selected `Solution Items` folder in the Solution Explorer window.

**Comment by Rob-Hague** [comment]
> I have done some research on this and with share bit of luck I have found out that this issue happens if I have selected `Solution Items` folder in the Solution Explorer window.

Legend, thanks

**Comment by jerviscui** [comment]
> I have done some research on this and with share bit of luck I have found out that this issue happens if I have selected `Solution Items` folder in the Solution Explorer window.

THX
